### ISSUE TITLE
url callback

### ISSUE THREAD

**Issue by LunaGrown** [derweili/fb-messenger-bot-for-woocommerce#1]
I have installed and url callback is not working according to FB api. is there a way to live test?

**Comment by derweili** [comment]
Sorry for the late reply, I just uploaded a new version of the plugin.
The new webhook url is: https://yoururl.com/wp-content/plugins/fb-messenger-bot-for-woocommerce/webhook.php

**Comment by LunaGrown** [comment]
I've updated to the new version and created an app with the webhook as above. I get this error (The URL couldn't be validated. Callback verification failed with the following errors: HTTP Status Code = 500; HTTP Message = Internal Server Error)

**Comment by derweili** [comment]
Did you replace "yoururl.com" with your site url?
Please also check if the plugin folder is called fb-messenger-bot-for-woocommerce.

If both is correct, open the webhook url with you browser. You should see a white screen. If there are some errors, please check your server settings.

**Comment by LunaGrown** [comment]
I thought it might be the server or haccess but this is the error: Parse error: syntax error, unexpected '}' in /home/chris/www/mysite/wp-content/plugins/fb-messenger-bot-for-woocommerce-master/webhook.php on line 75

**Comment by derweili** [comment]
Ok, download the latest version. There was an bug whithin the webhook funktion.

**Comment by LunaGrown** [comment]
this is the error I get now.:

Warning: file_put_contents(loghtml): failed to open stream: Permission denied in /home/chris/www/lunagrown/wp-content/plugins/fb-messenger-bot-for-woocommerce-master/webhook.php on line 17 Warning: file_put_contents(log.html): failed to open stream: Permission denied in /home/chris/www/lunagrown/wp-content/plugins/fb-messenger-bot-for-woocommerce-master/webhook.php on line 35

**Comment by derweili** [comment]
Please make the log.html file (inside the plugin folder) writable.

**Comment by LunaGrown** [comment]
Got it! Thank you. All seems to be running in testing. I don't see how the messenger bot requests (or pulls) FB messenger ID. Post checkout there is a notice "Get notified about Updates via Facebook Messenger" but no area to add ID or checkbox. Did I miss something else?

**Comment by derweili** [comment]
The "Get notified about Updates via Facebook Messenger" section should display the send to messenger button.

Please check if your credentials are correct.

Are you loggen in into your fb account? In development mode, only the developers of the fb app can see the button.

**Comment by LunaGrown** [comment]
Perfect, I missed the subscribe button on the app form. Beautiful job.
