### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by anishjajodia** [derweili/fb-messenger-bot-for-woocommerce#2]
Hello,

I loved the concept of the plugin. I wanted to know if this thing really works on a live wordpress/woocommerce website?

Do let me know.

Thanks.

**Comment by derweili** [comment]
I'm sorry for the late replay.
There where several bugs inside the plugin and I had no time to fix them until now.

I just updoaded a new version of the "fb messenger bot for woocommerce". Which works well with the latest version of WooCommerce and the Messenger API.
