### ISSUE TITLE
Call Back URL

### ISSUE THREAD

**Issue by LunaGrown** [derweili/fb-messenger-bot-for-woocommerce#5]
Hi, after the update I can't get the callback url to function. I get this warning by checking the url link directly, and on facebook I get the red X. I've double checked my api information. Any thoughts?

Best Regards

Warning: file_put_contents(log2.html): failed to open stream: Permission denied in /home/chris/www/lunagrown/wp-content/plugins/messenger-bot-for-woocommerce/webhook.php on line 17 Warning: file_put_contents(log2.html): failed to open stream: Permission denied in /home/chris/www/lunagrown/wp-content/plugins/messenger-bot-for-woocommerce/webhook.php on line 18

**Comment by derweili** [comment]
Please download the latest Update 1.4. This should solve this problem.

**Comment by derweili** [comment]
Hi, is everything working well? Can I close the issue?

**Comment by LunaGrown** [comment]
Hello Julian,

 

Yes my apologies, everything seems to be working fine. Thank you kindly.
