### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Juhenriqueta** [derweili/fb-messenger-bot-for-woocommerce#6]
Hi there!

The messenger is working fine, but it doesn’t show on firefox. I can see it fine from Safari only. I couldn’t find how to fix it. Could you please give me some help?

Many Thanks,
Juliana

**Comment by derweili** [comment]
It's working fine on my mac in all three browsers: Safari, Chrome and Firefox.
Which messenger plugin are you talking about? The checkbox plugin on the checkout page or the send-to-messenger plugin on the thank you page?

Is your app still in development mode? Facebook has some restrictions for apps in development mode. Some of the Messenger Plugins are only displayed to logged in admins of the facebook app.

**Comment by Juhenriqueta** [comment]
Hi, I’m talking about the checkbox plugin on the checkout page. The app is not in development mode. This is how I see the checkout page on Safari and Firefox:

![screen shot 2017-01-18 at 23 09 30](https://cloud.githubusercontent.com/assets/24597421/22126199/9a3db676-de8e-11e6-809c-a24ff1f5aabe.png)
![screen shot 2017-01-18 at 23 09 38](https://cloud.githubusercontent.com/assets/24597421/22126200/9a5b556e-de8e-11e6-846f-2d00e351131b.png)

Thanks!

**Comment by derweili** [comment]
Could you please send me a link to you page so I can check this error?

**Comment by Juhenriqueta** [comment]
https://ellorganics.co.uk/checkout/

**Comment by derweili** [comment]
I'm sorry. I can't access the Page. I always get redirected to the landingpage
> WE WILL LAUNCH SOMETHING AWESOME

**Comment by Juhenriqueta** [comment]
Sorry! you can access it now... https://ellorganics.co.uk/shop/

**Comment by derweili** [comment]
Hi, I checked your page in chrome and safari. It working for me but only If I'm logged in into my facebook account. (I'm still added as a developer to your app)
The app isn't in development mode but you submit your messenger app for review.

After the successfull review everyone can use the messenger functions.

**Comment by Juhenriqueta** [comment]
Hi. Ok. Thanks for the help!

**Comment by Juhenriqueta** [comment]
Just one more question? Have you tried it on Firefox? Because on Firefox even logged in into my facebook account I still can’t see the check box... Will it only show up after the review? Thanks!
