### ISSUE TITLE
No Check Box

### ISSUE THREAD

**Issue by beyourselfmarketing** [derweili/fb-messenger-bot-for-woocommerce#9]
I have an issue with no check box showing regardless of logged in or out status on facebook.

I have deleted the plugin and reinstalled the plugin and that has not fixed the issue. App is approved and public.

The plugin was working just fine when it was first setup but now I just see:
Contact Options

Receive updates in Messenger

NO TICK BOX, etc.

Also in the settings it lists domains that should no longer be whitelisted, how do I get rid of these?

Thank you
<img width="1234" alt="screenshot 2017-04-29 15 38 12" src="https://cloud.githubusercontent.com/assets/27777986/25556292/e5f5a0a4-2cf1-11e7-96f3-f8775f6b930d.png">

**Comment by ReignOfComputer** [comment]
Any updates to this? Came across this plugin and was going to use it, but it looks broken?

**Comment by beyourselfmarketing** [comment]
I believe this has been fixed as I no longer have the issue.

**Comment by ReignOfComputer** [comment]
Did you do anything in particular? I'm facing the same issue you experienced.

**Comment by beyourselfmarketing** [comment]
I don't recall. Very sorry. 



		
Jeffrey Euen-Gow
Business Manager, Be Yourself Marketing Ltd
07598712024  | jeff@beyourselfmarketing.co.uk  | http://beyourselfmarketing.co.uk | Unit 107, 1 Quality Court, London WC2A 1HR
 
​Be Yourself Marketing Ltd
Company Number: 07440633
VAT number GB139412026
Registered Office: Unit 107, 1 Quality Court, London WC2A 1HR

On 15 Jun 2017, at 15:38, ReignOfComputer <notifications@github.com> wrote:

Did you do anything in particular? I'm facing the same issue you experienced.
